# Generated by Django 4.2.7 on 2023-11-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Playlist Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Playlist created date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Latest playlist update')),
                ('songs', models.ManyToManyField(to='musik.song', verbose_name='Songs in Playlist')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
            },
        ),
    ]
